import Tree from './tree.js';

let tree = new Tree([1, 3, 2, 4]);
console.log(tree);
console.log(tree.isBalanced());
console.log(tree.levelOrder());
console.log(tree.preOrder());
console.log(tree.postOrder());
console.log(tree.inOrder());
tree.insert(5);
tree.insert(20);
tree.insert(10);
tree.insert(11);
tree.delete(11);
console.log(tree.isBalanced());
tree.rebalance();
console.log(tree.isBalanced());
console.log(tree.levelOrder());
console.log(tree.preOrder());
console.log(tree.postOrder());
console.log(tree.inOrder());
